// ------------------ HTML Templates --------------------------

// -------------- Period Edit Page ------------------------------
exports.periodEditPage = function (s, d) {
  return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Period Edit</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Period Edit</h2>
                </header>
        
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${s.nome}" required/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Update</button>
                </form>
        
                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/periodos">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `;
};

// -------------- Period Form Page ------------------------------
exports.periodFormPage = function (d) {
  return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Period Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Period Form</h2>
                </header>
        
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" required/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>
        
                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/periodos">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `;
};

// -------------- Composer Edit Page ------------------------------
exports.composerEditPage = function (s, d) {
  return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Edit</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Composer Edit</h2>
                </header>
        
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${s.nome}" required/>
                        <label>Periodo</label>
                        <input class="w3-input w3-round" type="text" name="periodo" value="${s.periodo}" required/>
                        <label>Biografia</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${s.bio}" required/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc" value="${s.dataNasc}" required/>
                        <label>Data de Morte</label>
                        <input class="w3-input w3-round" type="date" name="dataObito" value="${s.dataObito}" required/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Update</button>
                </form>
        
                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `;
};

// -------------- Composer Form Page ------------------------------
exports.composerFormPage = function (d) {
  return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Composer Form</h2>
                </header>
        
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Nome</label>
                        <input class="w3-input w3-round" type="text" name="nome" required/>
                        <label>Periodo</label>
                        <input class="w3-input w3-round" type="text" name="periodo" required/>
                        <label>Biografia</label>
                        <input class="w3-input w3-round" type="text" name="bio" required/>
                        <label>Data de Nascimento</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc" required/>
                        <label>Data de Morte</label>
                        <input class="w3-input w3-round" type="date" name="dataObito" required/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>
        
                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>
    `;
};

// -------------- Composer Page ------------------------------
exports.composerPage = function (s, d) {
  return `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>${s.nome}</h1>
                </header>
        
                <div class="w3-container">
                    <p>
                        <b>Id:</b> ${s.id}<br>
                        <b>Nome:</b> ${s.nome}<br>
                        <b>Periodo:</b>> ${s.periodo} <br>
                        <b>Biografia:</b> ${s.bio}<br>  
                        <b>Data de Nascimento:</b> ${s.dataNasc}<br>
                        <b>Data de Morte:</b> ${s.dataObito}<br>
                    </p>
                </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `;
};

// -------------- Composer Detail Page ------------------------------
exports.composerListPage = function (slist, d) {
  var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composers Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Composers List
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>periodo</th>
                        </tr>
                `;
  for (let i = 0; i < slist.length; i++) {
    pagHTML += `
                <tr>
                    <td>${slist[i].id}</td>
                    <td>
                        <a href="/compositor/${slist[i].id}">
                            ${slist[i].nome}
                        </a>
                    </td>
                    <td>${slist[i].periodo}</td>
                    <td>
                        [<a href="/compositores/edit/${slist[i].id}">Edit</a>][<a href="/compositores/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `;
  }

  pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `;
  return pagHTML;
};

// -------------- Periods List Page ------------------------------
exports.periodListPage = function (slist, d) {
  var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Periods Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Periods List
                    <a class="w3-btn w3-round w3-grey" href="/periodos/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                        </tr>
                `;
  for (let i = 0; i < slist.length; i++) {
    pagHTML += `
                <tr>
                    <td>${slist[i].id}</td>
                    <td>
                            ${slist[i].nome}
                    </td>
                    <td>
                        [<a href="/periodos/edit/${slist[i].id}">Edit</a>][<a href="/periodos/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `;
  }

  pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `;
  return pagHTML;
};

// -------------- Error Treatment ------------------------------
exports.errorPage = function (errorMessage, code) {
  return `
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ERROR ${code}</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        text-align: center;
        padding: 50px;
      }

      h1 {
        font-size: 36px;
        margin-bottom: 20px;
      }

      p {
        font-size: 18px;
        margin-bottom: 20px;
      }
    </style>
  </head>
  <body>
    <h1>ERROR ${code}</h1>
    <p>${errorMessage}</p>
  </body>
</html>
`;
};
